use crate::content::library::Library;

// app state: generated by Perplexity AI after I didn't know how I should carry the Library into
// Ratatui. It suggested creating a master 'App state'
pub struct App {
    library: Library,
    selected_series: usize,
    selected_book: usize,
    screen: Screen,
    should_quit: bool,
    dirty: bool, // has the data changed since last save?
}

enum Screen {
    SeriesList,
    BookList,
    BookDetails,
    EditBook,
}

impl App {
    pub fn new(library: Library) -> Self {
        Self {
            library,
            selected_series: 0,
            selected_book: 0,
            screen: Screen::SeriesList,
            should_quit: false,
            dirty: false,
        }
    }
}
