use crossterm::event::{KeyCode, KeyEvent};
use ratatui::widgets::TableState;

use crate::content::library::Library;

// app state: generated by Perplexity AI after I didn't know how I should carry the Library into
// Ratatui. It suggested creating a master 'App state'
pub struct App {
    pub library: Library,
    pub selected_series: usize,
    pub selected_book: usize,
    pub property_tab: usize, // might change type later
    pub screen: Screen,
    pub should_quit: bool,
    pub dirty: bool,
    pub should_show_help: bool, // has the data changed since last save?
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Screen {
    SeriesList,
    BookList,
    Properties,
}

impl Screen {
    fn left(self) -> Screen {
        match self {
            Screen::SeriesList => Screen::SeriesList, // don't wrap
            Screen::BookList => Screen::SeriesList,
            Screen::Properties => Screen::BookList,
        }
    }

    fn right(self) -> Screen {
        match self {
            Screen::SeriesList => Screen::BookList,
            Screen::BookList => Screen::Properties,
            Screen::Properties => Screen::Properties, // don't wrap
        }
    }
}

impl App {
    pub fn new(library: Library) -> Self {
        Self {
            library,
            selected_series: 0,
            selected_book: 0,
            property_tab: 0,
            screen: Screen::SeriesList,
            should_quit: false,
            dirty: false,
            should_show_help: false,
        }
    }

    pub fn on_key(&mut self, key: KeyEvent, table_state: &mut TableState) {
        // global shortcuts
        match key.code {
            KeyCode::Char('q') | KeyCode::Esc => {
                self.should_quit = true;
            }
            KeyCode::Char('?') => {
                self.should_show_help = true;
            }
            _ => {}
        }

        // movement keys
        match key.code {
            KeyCode::Char('H') => self.screen = self.screen.left(),
            KeyCode::Char('L') => self.screen = self.screen.right(),
            _ => {}
        }

        match self.screen {
            Screen::SeriesList => match key.code {
                KeyCode::Char('j') => {
                    if self.selected_series + 1 > self.library.series.len() {
                        self.selected_series = 0;
                    } else {
                        self.selected_series += 1;
                    }
                }
                KeyCode::Char('k') => {
                    // saturating_sub clamps value to 0 to avoid a panic
                    self.selected_series = self.selected_series.saturating_sub(1);
                }
                _ => {}
            },
            Screen::BookList => match key.code {
                KeyCode::Char('j') | KeyCode::Down => table_state.select_next(),
                KeyCode::Char('k') | KeyCode::Up => table_state.select_previous(),
                KeyCode::Char('l') | KeyCode::Right => table_state.select_next_column(),
                KeyCode::Char('h') | KeyCode::Left => table_state.select_previous_column(),
                KeyCode::Char('g') => table_state.select_first(),
                KeyCode::Char('G') => table_state.select_last(),
                _ => {}
            },
            Screen::Properties => match key.code {
                KeyCode::Tab | KeyCode::Char('h') | KeyCode::Char('l') => {
                    // toggle
                    if self.property_tab == 0 {
                        self.property_tab = 1;
                    } else {
                        self.property_tab = 0;
                    }
                }
                _ => {}
            },
        }
    }
}
