[[series]]
title = "Some Series"

[[series.books]]
genre = "FANTASY"
total_pages = 112
author = "John Doe"
title = "Foo"
times_read = 1
is_owned = false

[[series.books]]
genre = "FANTASY"
total_pages = 112
author = "John Doe"
title = "Bar"
times_read = 1
is_owned = false

[[series.books]]
genre = "FANTASY"
total_pages = 112
author = "John Doe"
title = "FooBar"
times_read = 1
is_owned = false
[[series]]
title = "Some Series"

[[series.books]]
genre = "FANTASY"
total_pages = 112
author = "John Doe"
title = "Foo"
times_read = 1
is_owned = false

[[series.books]]
genre = "FANTASY"
total_pages = 112
author = "John Doe"
title = "Bar"
times_read = 1
is_owned = false

[[series.books]]
genre = "FANTASY"
total_pages = 11
author = "John Doe"
title = "FooBar"
times_read = 1
is_owned = false

[[standalone_books]]
genre = "FANTASY"
total_pages = 11
author = "John Doe"
title = "FooBar"
times_read = 1
is_owned = false
